### ISSUE TITLE
The code of ActivityNet

### ISSUE THREAD

**Issue by mugenggeng** [TuanTNG/SimOn#1]
We are very sorry to bother you. We are very interested in your research and urgently hope that you can provide the code details on the ActivityNet dataset. Thank you very much

**Comment by TuanTNG** [comment]
Hi, 
Sorry for the late reply. 
Currently, our team does not have the plan to release the code for ActivityNet. However, you can download the pre-extracted feature from here https://github.com/frostinassiky/gtad and train SimOn using the provided code on THUMOS.
