### ISSUE TITLE
Feature extraction code

### ISSUE THREAD

**Issue by wrko** [TuanTNG/SimOn#4]
I want to test your wonderful algorithm with an other dataset. Can you provide the pretrained TSN models you used and the code for feature extraction

**Comment by TuanTNG** [comment]
Hi @wrko,
Thank you for your interest in our work. 
Sorry for the late reply.

In this work, we trained the model using extracted features from OadTR, https://github.com/wangxiang1230/OadTR.
You can refer to OadTr to see where the pre-trained TSN model they used is. 

If you have any further questions, please let me know.
